### ISSUE TITLE
Failure due to incompatible unit string in lquota output

### ISSUE THREAD

**Issue by aidanheerdegen** [coecms/dumpstats#21]
Seems that the last update failed due to an incompatible unit appearing in `/g/data/hh5/admin/analytics/logs/2023-07-17T18:34:17.lquota.dump`

https://accessdev.nci.org.au/jenkins/blue/organizations/jenkins/CLEX%20Admin%2Fdump_stats/detail/dump_stats/1344/pipeline

Specifically
```
$ grep ' B ' /g/data/hh5/admin/analytics/logs/2023-07-17T18:34:17.lquota.dump
  kj13 scratch  12.00 KiB     0.00 B     0.00 B        3        0        0
$
```

The parsing expects an `iB` unit.

**Comment by dsroberts** [comment]
Took a while, but the update ncigrafana conda package has been published. Update your stats conda env and you should pick it up.
